name: Development Pipeline

on:
  push:
    branches:
      - dev

jobs:
  dev-pipeline:
    uses: ./.github/workflows/reusable-workflow.yml
    with:
      environment: development
    secrets:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      AWS_REGION: ${{ secrets.AWS_REGION }}
      BUCKET_NAME: ${{ secrets.DEV_BUCKET_NAME }}
