name: Production Pipeline

on:
  workflow_dispatch:
    inputs:
      confirmDeploy:
        description: "Confirm production deployment"
        required: true
        type: boolean

jobs:
  prod-pipeline:
    if: inputs.confirmDeploy == true
    uses: ./.github/workflows/reusable-workflow.yml
    with:
      environment: production
    secrets:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      AWS_REGION: ${{ secrets.AWS_REGION }}
      BUCKET_NAME: ${{ secrets.PROD_BUCKET_NAME }}
