name: Test Pipeline

on:
  push:
    branches:
      - test

jobs:
  test-pipeline:
    uses: ./.github/workflows/reusable-workflow.yml
    with:
      environment: test
    secrets:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      AWS_REGION: ${{ secrets.AWS_REGION }}
      BUCKET_NAME: ${{ secrets.TEST_BUCKET_NAME }}
